#!/bin/bash



#Script criado para atividade de infraestrutura como codigo da DIO#


mkdir publico
mkdir adm
mkdir ven
mkdir sec

groupadd GRP_ADM
groupadd GRP_VEN
groupadd GRP_SEC

useradd carlos -m -s /bin/bash -g GRP_ADM -p $(openssl passwd -rypt isakclol) -e

useradd carlos -m -c "Novo usuário do grupo ADM" -s /bin/bash -g GRP_ADM -p $(openssl passwd -rypt isakclol) -e

useradd maria -m -c "Novo usuário do grupo ADM" -s /bin/bash -g GRP_ADM -p $(openssl passwd -rypt isakclol) -e

useradd joao -m -c "Novo usuário do grupo ADM" -s /bin/bash -g GRP_ADM -p $(openssl passwd -rypt isakclol) -e

useradd debora -m -c "Novo usuário do grupo VEN" -s /bin/bash -g GRP_VEN -p $(openssl passwd -rypt isakclol) -e

useradd sebastiana -m -c "Novo usuário do grupo VEN" -s /bin/bash -g GRP_VEN -p $(openssl passwd -rypt isakclol) -e

useradd roberto -m -c "Novo usuário do grupo VEN" -s /bin/bash -g GRP_VEN -p $(openssl passwd -rypt isakclol) -e

useradd josefina -m -c "Novo usuário do grupo SEC" -s /bin/bash -g GRP_SEC -p $(openssl passwd -rypt isakclol) -e

useradd amanda -m -c "Novo usuário do grupo SEC" -s /bin/bash -g GRP_SEC -p $(openssl passwd -rypt isakclol) -e

useradd rogerio -m -c "Novo usuário do grupo SEC" -s /bin/bash -g GRP_SEC -p $(openssl passwd -rypt isakclol) -e

chown root publico
chown root adm
chown root ven
chown root sec

chgrp GRP_ADM adm
chgrp GRP_VEN ven
chgrp GRP_SEC sec


chmod 777 publico
chmod 770 adm
chmod 770 ven
chmod 770 sec
